mutation addshippingaddress($address1: String, $address2: String, $city: String, $state: String, $postalCode: String, $country: String) {
    addshippingaddress(data: {
        address1: $address1
        address2: $address2
        city: $city
        state: $state
        postalCode: $postalCode
        country: $country
    }) {
        Model {
            _id
            address1
            address2
            city
            state
            city
            postalCode
            country
        }
        Successful
        Message
    }
}