query getrecentlysold {
    getrecentlysold {
        _id
        artwork {
            _id
            title
            pictures
            year
            artist {
                _id
                fullName
            }
        }
        price
    }
}