mutation updateprofile($_id: ID!, $firstName: String, $lastName: String, $birthdate: String, $displayPicture: String, $mobileNumber: String, $gender: String, $address1: String, $city: String, $state: String, $postalCode: String, $country: String) {
    updateprofile(data: {
        _id: $_id
        firstName: $firstName
        lastName: $lastName
        birthdate: $birthdate
        displayPicture: $displayPicture
        mobileNumber: $mobileNumber
        gender: $gender
        address1: $address1
        city: $city
        state: $state
        postalCode: $postalCode
        country: $country
    }) {
        Model {
            _id
            firstName
            lastName
            fullName
            displayPicture
            gender
            mobileNumber
            birthdate
            address1
            city
            state
            postalCode
            country
        }
        Successful
        Message
    }
}