mutation addpaymentmethod($cardNumber: String, $cardType: String, $paymentType: String, $token: String, $accountName: String) {
    addpaymentmethod(data: {
        accountName: $accountName
        cardNumber: $cardNumber
        cardType: $cardType
        paymentType: $paymentType
        token: $token
    }) {
        Model {
            _id
            paymentType
            cardType
            cardNumber
            accountName
        }
        Successful
        Message
    }
}